/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteRouteImport } from './routes/_admin/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminIndexRouteImport } from './routes/_admin/index'
import { Route as AdminDrawsRouteImport } from './routes/_admin/draws'
import { Route as AdminTicketsRouteImport } from './routes/_admin/tickets'
import { Route as AdminUsersRouteImport } from './routes/_admin/users'
import { Route as AdminWinnersRouteImport } from './routes/_admin/winners'

const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDrawsRoute = AdminDrawsRouteImport.update({
  id: '/draws',
  path: '/draws',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTicketsRoute = AdminTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminWinnersRoute = AdminWinnersRouteImport.update({
  id: '/winners',
  path: '/winners',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AdminIndexRoute
  '/login': typeof LoginRoute
  '/draws': typeof AdminDrawsRoute
  '/tickets': typeof AdminTicketsRoute
  '/users': typeof AdminUsersRoute
  '/winners': typeof AdminWinnersRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/draws': typeof AdminDrawsRoute
  '/tickets': typeof AdminTicketsRoute
  '/users': typeof AdminUsersRoute
  '/winners': typeof AdminWinnersRoute
  '/': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_admin/draws': typeof AdminDrawsRoute
  '/_admin/tickets': typeof AdminTicketsRoute
  '/_admin/users': typeof AdminUsersRoute
  '/_admin/winners': typeof AdminWinnersRoute
  '/_admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/draws' | '/tickets' | '/users' | '/winners'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/draws' | '/tickets' | '/users' | '/winners' | '/'
  id:
    | '__root__'
    | '/_admin'
    | '/login'
    | '/_admin/draws'
    | '/_admin/tickets'
    | '/_admin/users'
    | '/_admin/winners'
    | '/_admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/': {
      id: '/_admin/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/draws': {
      id: '/_admin/draws'
      path: '/draws'
      fullPath: '/draws'
      preLoaderRoute: typeof AdminDrawsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/tickets': {
      id: '/_admin/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof AdminTicketsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/users': {
      id: '/_admin/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/winners': {
      id: '/_admin/winners'
      path: '/winners'
      fullPath: '/winners'
      preLoaderRoute: typeof AdminWinnersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminDrawsRoute: typeof AdminDrawsRoute
  AdminTicketsRoute: typeof AdminTicketsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWinnersRoute: typeof AdminWinnersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminDrawsRoute: AdminDrawsRoute,
  AdminTicketsRoute: AdminTicketsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWinnersRoute: AdminWinnersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AdminRouteRoute: AdminRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
